# Generated by Django 6.0.6 on 2026-07-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_heroslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=300)),
                ('icon_class', models.CharField(default='fa-solid fa-solar-panel', help_text="Font Awesome icon class shown on the badge, e.g. 'fa-solid fa-house'", max_length=100)),
                ('image', models.ImageField(blank=True, help_text='Photo shown at the top of the card', null=True, upload_to='solutions/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Solar Solutions',
                'ordering': ['order', 'id'],
            },
        ),
    ]
