# Generated by Django 6.0.6 on 2026-07-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_solarsolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarsolution',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='Optional: used only if no photo is uploaded above (e.g. a temporary stock photo link).'),
        ),
        migrations.AlterField(
            model_name='solarsolution',
            name='image',
            field=models.ImageField(blank=True, help_text='Photo shown at the top of the card. Uploading here always overrides the link below.', null=True, upload_to='solutions/'),
        ),
    ]
