# Generated by Django 6.0.7 on 2026-07-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_seed_solar_solutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='Optional: used only if no photo is uploaded above (e.g. a temporary stock photo link).'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(blank=True, help_text='Uploading here always overrides the link below.', null=True, upload_to='hero_slides/'),
        ),
    ]
