# Generated by Django 6.0.7 on 2026-07-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_seed_hero_slides'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Residential Project', max_length=200)),
                ('description', models.CharField(help_text='e.g. 5KW Rooftop Solar Installation.', max_length=300)),
                ('image', models.ImageField(blank=True, help_text='Photo shown on the card. Uploading here always overrides the link below.', null=True, upload_to='projects/')),
                ('image_url', models.URLField(blank=True, default='', help_text='Optional: used only if no photo is uploaded above (e.g. a temporary stock photo link).')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'ordering': ['order', 'id'],
            },
        ),
    ]
