# Generated by Django 6.0.7 on 2026-07-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='icon_class',
            field=models.CharField(default='fa-solid fa-solar-panel', help_text="Font Awesome icon class shown on the badge, e.g. 'fa-solid fa-house'", max_length=100),
        ),
    ]
