# Generated by Django 6.0.7 on 2026-07-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_project_icon_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Rooftop Array', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='e.g. Residential Installation', max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Uploading here always overrides the link below.', null=True, upload_to='gallery/')),
                ('image_url', models.URLField(blank=True, default='', help_text='Optional: used only if no photo is uploaded above (e.g. a temporary stock photo link).')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order', 'id'],
            },
        ),
    ]
