# Generated by Django 5.2.16 on 2026-07-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mr. Owner Name', max_length=200)),
                ('role', models.CharField(default='Owner, Founder & Director', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='founder/')),
                ('bio', models.TextField(default='With a passion for renewable energy and innovation, Mr. Owner Name started Shine Solar Energy with a vision to provide dependable solar solutions.')),
                ('skills', models.TextField(default='Solar Energy Solutions\nProject Management\nCustomer Service\nRenewable Energy Development', help_text='Enter one skill per line')),
            ],
            options={
                'verbose_name_plural': 'Founder Details',
            },
        ),
    ]
